In [1]:
import numpy as np

# Basic

In [8]:
a = np.array([1,2,3],dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [3]:
b= np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [9]:
# Get type
print(a.dtype)
print(b.dtype)

int16
float64


In [10]:
# Get Size
print(a.itemsize)
print(b.itemsize)

2
8


In [12]:
# Get total size
print(a.size*a.itemsize)
print(b.size*b.itemsize)

6
48


In [13]:
print(a.nbytes)
print(b.nbytes)

6
48


# Accessing rows,columns,etc

In [14]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
c.shape

(2, 7)

In [16]:
# Get a specific element [row, col]
c[1,5]

13

In [17]:
c[1,-4]

11

In [18]:
# Get a specific row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Geta specific col
c[:,3]

array([ 4, 11])

In [21]:
c[0,1::2]

array([2, 4, 6])

In [22]:
c[1,5]=20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
c[:,2]=5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [25]:
c[:,2]=[1,2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3d-example

In [26]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
# Get specific element
d[0,1,1]

4

In [28]:
d[0,1,:]

array([3, 4])

In [29]:
d[:,1,1]

array([4, 8])

In [30]:
d[0,:,1]

array([2, 4])

In [31]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [32]:
d[:,1,:]=[[9,9],[10,10]]
print(d)

[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [10 10]]]


# Initializing diff types of Array 

In [34]:
# All 0s matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
# All 1s matrix
np.ones((4,2),dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [37]:
# Any other values
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [39]:
# Any other values (full_like)
np.full_like(d,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [41]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.24196269, 0.77755214, 0.17488913],
       [0.86700573, 0.07751506, 0.63407899]])

In [42]:
np.random.random_sample(d.shape)

array([[[0.4619322 , 0.77620096],
        [0.03861343, 0.30331429]],

       [[0.22575824, 0.06221149],
        [0.72109661, 0.59471147]]])

In [44]:
# Random integer value
np.random.randint(-4,7,size=(3,3))

array([[-3,  4, -4],
       [-2, -2,  5],
       [ 3,  0, -2]])

In [45]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [49]:
r2 = np.repeat(arr,3,axis=1)
r2

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [63]:
# Questions answer
# temp = np.zeros((5,5),dtype='int32')
# temp[0,:] = np.ones(5)
# temp[:,0] = np.ones(5)
# temp[4,:] = np.ones(5)
# temp[:,4] = np.ones(5)
# temp[2,2] = 9
# temp
temp = np.ones((5,5))
temp[1:4,1:4] = np.zeros((3,3))
temp[2,2] = 9
temp

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Mathematics

In [64]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [65]:
a + 2

array([3, 4, 5, 6])

In [66]:
a - 2

array([-1,  0,  1,  2])

In [67]:
a*2

array([2, 4, 6, 8])

In [68]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [70]:
a += 2 
a

array([5, 6, 7, 8])

In [71]:
b = np.array([4,5,6,7])
a + b

array([ 9, 11, 13, 15])

In [72]:
a ** 2

array([25, 36, 49, 64])

In [73]:
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [74]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

# Linear Algebra

In [75]:
a = np.full((2,3),1)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [76]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [77]:
# find the matrix multiplication
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [80]:
# find the determinant
a = np.array([[1,2,3],[4,5,6],[5,6,7]])
np.linalg.det(a)

3.330669073875456e-15

In [82]:
# find the inverse
np.linalg.inv(a)

array([[-3.00239975e+14,  1.20095990e+15, -9.00719925e+14],
       [ 6.00479950e+14, -2.40191980e+15,  1.80143985e+15],
       [-3.00239975e+14,  1.20095990e+15, -9.00719925e+14]])

In [83]:
# find the eigen values
np.linalg.eig(a)

(array([ 1.38654599e+01, -8.65459931e-01, -6.19451544e-17]),
 array([[ 0.26830632,  0.8780304 ,  0.40824829],
        [ 0.62003176, -0.12665002, -0.81649658],
        [ 0.73727358, -0.46154349,  0.40824829]]))

# Statistics

In [84]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# min of array
np.min(stats)

1

In [86]:
# max of array
np.max(stats)

6

In [87]:
# min of first row
np.min(stats,axis=1)

array([1, 4])

In [88]:
# sum of array
np.sum(stats)

21

In [89]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [90]:
np.sum(stats,axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [91]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
before.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [93]:
before.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [96]:
# Vertically stacking vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [100]:
arr = np.genfromtxt('/Users/sakshamtaneja/Desktop/python/text.txt',delimiter=',')
arr

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [102]:
arr = arr.astype('int32')
arr

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

Advance Indexing and Boolean Masking

In [103]:
arr > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [104]:
arr[arr>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [105]:
# you can index a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [106]:
np.any(arr>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [107]:
np.all(arr>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [109]:
((arr>50) & (arr<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [110]:
(~((arr>50) & (arr<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])